from dataclasses import dataclass
from enum import Enum
from typing import Protocol, Self, TypeVar

from seriacade.json.interfaces import JsonCodecWithSchemaProtocol
from seriacade.json.types import JsonType


class ChatRole(Enum):
    """ADT for chat roles."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


T = TypeVar("T")


@dataclass
class ChatMessage:
    """Represents a message in a chat session.

    Abstracts over the different Langchain message types using ChatRole ADT.
    """

    role: ChatRole
    # Support any for compatibility with langchain
    # TODO: Cleanup these later, don't like having typing exceptions in the higher level abstraction
    content: str | list[str | dict[str, "JsonType"]]
    response_metadata: JsonType | None = None
    id: str | None = None
    usage_metadata: JsonType | None = None


class ChatLLMProtocol(Protocol):
    """Protocol for a chat language model.

    This protocol defines the interface for a chat language model, including
    synchronous and asynchronous methods for sending messages and configuring
    structured output.
    """

    structured_output: dict[str, JsonType] | None

    def chat(self, messages: list[ChatMessage]) -> ChatMessage:
        """Sends a list of chat messages to the language model and returns a response message.

        Args:
            messages (list[ChatMessage]): A list of chat messages to be sent to the language model.

        Returns:
            ChatMessage: The response message generated by the language model.
        """
        ...

    async def async_chat(self, messages: list[ChatMessage]) -> ChatMessage:
        """Asynchronously sends a list of chat messages to the language model and returns a response message.

        Args:
            messages (list[ChatMessage]): A list of chat messages to be sent to the language model.

        Returns:
            ChatMessage: The response message generated by the language model.
        """
        ...

    def with_structured_output(
        self, structured_output: dict[str, JsonType] | JsonCodecWithSchemaProtocol[T] | None
    ) -> Self:
        """Configures the chat model to use structured output with a specified schema.

        Args:
            structured_output (dict[str, JsonType] | JsonCodecWithSchemaProtocol[T] | None):
                A dictionary defining the schema for structured output or a codec
                that can serialize/deserialize the output. If None, structured output
                is disabled.

        Returns:
            Self: A new instance of the chat model with the structured output
                configuration applied.
        """
        ...
