from dataclasses import dataclass
from typing import Any, Protocol, TypeVar, assert_never

from zmq import Enum

from rag_resume.json import JsonCodecProtocol, JsonDecoderProtocol


class ChatRole(Enum):
    """ADT for chat roles."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


T = TypeVar("T")


@dataclass
class ChatMessage:
    """Represents a message in a chat session.

    Abstracts over the different Langchain message types using ChatRole ADT.
    """

    role: ChatRole
    content: str | list[str | dict[str, Any]]
    response_metadata: dict | None = None
    id: str | None = None
    usage_metadata: dict | None = None

    def decode_content(self, codec: JsonDecoderProtocol[T]) -> T:
        """Helper to decode content using a json decoder."""
        match self.content:
            case str():
                return codec.decode_json(self.content.encode())
            case list():
                return codec.convert_json(self.content)
            case _:
                assert_never(self)


class ChatLLMProtocol(Protocol):
    """Protocol for a chat language model."""

    def chat(self, messages: list[ChatMessage]) -> ChatMessage:
        """Sends a list of chat messages to the language model and returns a response message.

        Args:
            messages (list[ChatMessage]): A list of chat messages to be sent to the language model.

        Returns:
            ChatMessage: The response message generated by the language model.
        """
        ...

    async def async_chat(self, messages: list[ChatMessage]) -> ChatMessage:
        """Asynchronously sends a list of chat messages to the language model and returns a response message.

        Args:
            messages (list[ChatMessage]): A list of chat messages to be sent to the language model.

        Returns:
            ChatMessage: The response message generated by the language model.
        """
        ...

    @property
    def structured_output(self) -> dict[str, Any] | None:
        """Property for the structured output definition.

        Can be set with a provided json schema or derive the json schema from JsonCodecProtocol.

        Returns:
            dict[str, Any] | None: A json schema for the structured output.
        """
        ...

    @structured_output.setter
    def structured_output(self, schema: dict[str, Any] | JsonCodecProtocol | None) -> dict[str, Any] | None: ...
