from collections.abc import Sequence
from dataclasses import dataclass
from enum import Enum
from typing import Any, Protocol, TypeVar

from seriacade.json.interfaces import JsonCodecProtocol, JsonCodecWithSchemaProtocol
from seriacade.json.types import JsonType


class ChatRole(Enum):
    """ADT for chat roles."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


T = TypeVar("T")


@dataclass
class ChatMessage:
    """Represents a message in a chat session.

    Abstracts over the different Langchain message types using ChatRole ADT.
    """

    role: ChatRole
    # Support any for compatibility with langchain
    # TODO: Cleanup these later, don't like having typing exceptions in the higher level abstraction
    content: str | list[str | dict[str, Any]]  # pyright: ignore[reportExplicitAny]
    response_metadata: dict[str, Any] | None = None  # pyright: ignore[reportExplicitAny]
    id: str | None = None
    usage_metadata: dict[str, Any] | None = None  # pyright: ignore[reportExplicitAny]

    def decode_content(self, codec: JsonCodecProtocol[T]) -> T | Sequence[T]:
        """Helper to decode content using a json decoder."""
        match self.content:
            case str():
                return codec.decode_json(self.content.encode())
            case list():
                return [codec.convert_from_json(content) for content in self.content]


class ChatLLMProtocol(Protocol):
    """Protocol for a chat language model."""

    def chat(self, messages: list[ChatMessage]) -> ChatMessage:
        """Sends a list of chat messages to the language model and returns a response message.

        Args:
            messages (list[ChatMessage]): A list of chat messages to be sent to the language model.

        Returns:
            ChatMessage: The response message generated by the language model.
        """
        ...

    async def async_chat(self, messages: list[ChatMessage]) -> ChatMessage:
        """Asynchronously sends a list of chat messages to the language model and returns a response message.

        Args:
            messages (list[ChatMessage]): A list of chat messages to be sent to the language model.

        Returns:
            ChatMessage: The response message generated by the language model.
        """
        ...

    @property
    def structured_output(self) -> dict[str, JsonType] | None:
        """Property for the structured output definition.

        Can be set with a provided json schema or derive the json schema from JsonCodecProtocol.

        Returns:
            dict[str, Any] | None: A json schema for the structured output.
        """
        ...

    def with_structured_output(
        self, schema: dict[str, JsonType] | JsonCodecWithSchemaProtocol[T] | None
    ) -> dict[str, JsonType] | None: ...
